# .air.toml
# Configuring Air to work with Fiber

# Watch for changes in these directories
# Default is ['.']
root = "cmd"

# Where to store the pid of the running app.
pid_file = "air.pid"

# Build the app in this directory.
# Default is "tmp"
tmp_dir = "tmp"

# Whether to run tests after build.
run_tests = false

# Build binary name
build = "main"  # This is your compiled binary

# Log file
log = "air.log"

# Reload only on code changes
watch_dir = [
    "main.go",  # Add your main.go file and any other files
    "handlers",
    "models",
    "routes"
]

# For Fiber
cmd = "go run main.go"  # Or use `go build` if you're compiling the app

# Set your build's output directory (this is where the binary is placed)
bin = "tmp/main"  # Optional, for building the binary

# Optional: Set the log level (debug, info, warn, error)
log_level = "debug"
