version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: task_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379" # Exposing Redis default port
    volumes:
      - redis-data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"] # Enables persistence

volumes:
  mysql-data:
  redis-data:
